apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamento
  labels:
    app: pagamento
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pagamento
  template:
    metadata:
      name: pagamento
      labels:
        app: pagamento
    spec:
      containers:
        - name: pagamento
          image: localhost:32000/service-pagamento:${tag_version}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: pagamento-env-config
          env:
            - name: POR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-pagamento-secret
                  key: MONGO_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
            limits:
              memory: "256Mi"
              cpu: "0.5"
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
            terminationGracePeriodSeconds: 15
          startupProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
            terminationGracePeriodSeconds: 15
      restartPolicy: Always
