apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro
  namespace: tap-on-phone
  labels:
    app: cadastro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadastro
  template:
    metadata:
      name: cadastro
      labels:
        app: cadastro
    spec:
      containers:
        - name: cadastro
          image: localhost:32000/service-cadastro:1.0.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "1"
            limits:
              memory: "256Mi"
              cpu: "1"
      restartPolicy: Always
