kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: cadastro
  namespace: tap-on-phone
spec:
  maxReplicas: 3
  scaleTargetRef:
    kind: Deployment
    name: cadastro
    apiVersion: apps/v1
  minReplicas: 1
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
