apiVersion: v1
kind: Service
metadata:
  labels:
    app: cadastro
  name: cadastro
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: cadastro
  type: ClusterIP
