apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: tap-on-phone-database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgresql
  serviceName: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16.1-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-password
                  key: password

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
