apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: tap-on-phone-database
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
