kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: postgresql
  namespace: tap-on-phone-database
spec:
  maxReplicas: 3
  scaleTargetRef:
    kind: Deployment
    name: postgresql
    apiVersion: apps/v1
  minReplicas: 1
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
