version: '3.9'

services:
  cadastro:
    build:
      context: ./services/cadastro
    image: service-cadastro
    restart: always
    container_name: service-cadastro
    ports:
      - "8081:8080"
    volumes:
      - maven-repo:/root/.m2
    networks:
      - tap-on-phone
    mem_reservation: 268435456

  operacao-pagamento:
    build:
      context: ./services/operacao-pagamento
    image: service-operacao-pagamento
    restart: always
    container_name: service-operacao-pagamento
    ports:
      - "8082:8080"
    volumes:
      - maven-repo:/root/.m2
    networks:
      - tap-on-phone
    mem_reservation: 268435456

  motor-pagamento:
    build:
      context: ./services/motor-pagamento
    image: service-motor-pagamento
    restart: always
    container_name: service-motor-pagamento
    volumes:
      - maven-repo:/root/.m2
    networks:
      - tap-on-phone
    mem_reservation: 268435456

  pagamento:
    build:
      context: ./services/pagamento
    image: service-pagamento
    restart: always
    container_name: service-pagamento
    ports:
      - "8083:8080"
    volumes:
      - maven-repo:/root/.m2
    networks:
      - tap-on-phone
    mem_reservation: 268435456

  gateway:
    build:
      context: ./services/gateway
    image: service-gateway
    restart: always
    container_name: service-gateway
    ports:
      - "8080:8080"
    volumes:
      - maven-repo:/root/.m2
    networks:
      - tap-on-phone
    mem_reservation: 268435456

volumes:
  maven-repo:

networks:
  tap-on-phone:
    external: true
