version: '3.9'

services:
  postgresql:
    build:
      context: ./infra/postgresql
    image: postgresql-cadastro
    restart: always
    container_name: postgresql-cadastro
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
      POSTGRES_DB: cadastro
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tap-on-phone
    mem_reservation: 268435456

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: cp-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - tap-on-phone
    mem_reservation: 268435456

  kafka:
    image: confluentinc/cp-kafka
    container_name: cp-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - tap-on-phone
    mem_reservation: 268435456

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tap-on-phone
    mem_reservation: 268435456

  mongo:
    image: mongo
    #container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - tap-on-phone
    mem_reservation: 268435456

volumes:
  postgresql-data:
  mongodb-data:

networks:
  tap-on-phone:
    external: true
