spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
  data:
    mongodb:
      database: ${MONGO_DB_DATABASE}
      host: ${MONGO_DB_HOST}
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      authenticationDatabase: admin
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

rate-limit:
  limitRefreshPeriod: 10
  limitForPeriod: 5
  timeoutDuration: 3
  maxConcurrentCalls: 2

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

dead-letter:
  topic: ${DEAD_LETTER_TOPIC}
big-data:
  topic: ${BIG_DATA_TOPIC}
