apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database-storage-class
  namespace: tap-on-phone-database
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
