kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-persistent-volume-claim
  namespace: tap-on-phone-database
spec:
  storageClassName: database-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ki
