apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgpool
  namespace: tap-on-phone-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  serviceName: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: pgpool
          image: bitnami/pgpool:4.5.0
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgpool
          env:
            - name: PGPOOL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-password
                  key: password
            - name: PGPOOL_ADMIN_USERNAME
              value: "postgres"
            - name: PGPOOL_SR_CHECK_USER
              value: "postgres"
            - name: PGPOOL_SR_CHECK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-password
                  key: password
            - name: PGPOOL_POSTGRES_USERNAME
              value: "postgres"
            - name: PGPOOL_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-password
                  key: password
            - name: PGPOOL_BACKEND_NODES
              value: "0:postgresql-0.postgresql.tap-on-phone-database:5432,1:postgresql-1.postgresql.tap-on-phone-database:5432,2:postgresql-2.postgresql.tap-on-phone-database:5432"
            - name: PGPOOL_ENABLE_LOAD_BALANCING
              value: "yes"
            - name: PGPOOL_ENABLE_LDAP
              value: "no"
            - name: PGPOOL_ENABLE_LOG_CONNECTIONS
              value: "yes"
            - name: PGPOOL_ENABLE_LOG_HOSTNAME
              value: "yes"
          livenessProbe:
            exec:
              command:
                - /opt/bitnami/scripts/pgpool/healthcheck.sh
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - bash
                - -ec
                - PGPASSWORD=${PGPOOL_POSTGRES_PASSWORD} psql -U "postgres" -d "postgres" -h /opt/bitnami/pgpool/tmp -tA -c "SELECT 1" >/dev/null
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
