apiVersion: apps/v1
kind: Deployment
metadata:
  name: motor-pagamento
  namespace: tap-on-phone
  labels:
    app: motor-pagamento
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: motor-pagamento
  template:
    metadata:
      name: motor-pagamento
      labels:
        app: motor-pagamento
    spec:
      containers:
        - name: motor-pagamento
          image: localhost:32000/service-motor-pagamento:${MOTOR_PAGAMENTO_VERSION}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-motor-pagamento-secret
                  key: POSTGRES_PASSWORD
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
            limits:
              memory: "256Mi"
              cpu: "0.5"
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
      restartPolicy: Always
