apiVersion: v1
kind: Service
metadata:
  name: pgpool-service-external
  namespace: tap-on-phone-database
spec:
  type: NodePort
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app: pgpool
