server:
  port: 8082

dead-letter:
  topic: "dead-letter"

big-data:
  topic: "big-data"

spring:
  kafka:
    bootstrap-servers: "localhost:29092"
  cloud:
    openfeign:
      client:
        config:
          dadosPagamento-service:
            url: http://localhost:8081/api/v1/devices/
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: debug
