spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
  cloud:
    openfeign:
      client:
        config:
          dadosPagamento-service:
            url: ${DADOS_PAGAMENTO_SERVICE_URL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

rate-limit:
  limitRefreshPeriod: 10
  limitForPeriod: 5
  timeoutDuration: 3
  maxConcurrentCalls: 2

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

dead-letter:
  topic: "dead-letter"

pagamento-efetuado:
  topic: "pagamento-efetuado"

pagamento-atualizado:
  topic: "pagamento-atualizado"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
