apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database-storage-class
  namespace: tap-on-phone-database
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-persistent-volume
  namespace: tap-on-phone-database
spec:
  storageClassName: database-storage-class
  capacity:
    storage: 1Ki
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/database"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-persistent-volume-claim
  namespace: tap-on-phone-database
spec:
  storageClassName: database-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ki
