kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-persistent-volume
spec:
  storageClassName: mongodb-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/kubernetes/database/mongodb"
    type: DirectoryOrCreate
