kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-persistent-volume-claim
spec:
  storageClassName: mongodb-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
