apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-node-port
      protocol: TCP
      port: 29092
      targetPort: 29092
  type: NodePort
