spring:
  data:
    mongodb:
      database: ${MONGO_DB_DATABASE}
      host: ${MONGO_DB_HOST}
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    consumer:
      group-id: motor-pagamento
    retry:
      topic:
        attempts: ${KAFKA_RETRIES}
        max-interval: ${KAFKA_RETRIES_INTERVAL}
        multiplier: ${KAFKA_RETRIES_MULTIPLIER}
        initial: ${KAFKA_RETRIES_INITIAL}

pagamento-atualizado:
  topic: pagamento-atualizado
pagamento-efetuado:
  topic: pagamento-efetuado

dead-letter:
  topic: ${DEAD_LETTER_TOPIC}
big-data:
  topic: ${BIG_DATA_TOPIC}
